Phonons
wannier-berri/wannier-berri pull request #191
Opened 2022-06-10 02:12 UTC by stepan-tsirkin

Reading Phonons form QuantumEspresso AND INTERPOLATING THEM

So far implemented interpolation of phonon frequencies and phonon DOS and cumDOS. To be tested.

2022-09-27 18:27 UTC, stepan-tsirkin commented
I did some tests, looks to agree, and seems faster than the `dynmat.x` . @jaemolihm , you have some experience with phonons, right? could you try it and provide some feedback?  As you understand, it is a step towards electron-phonon interactions.

2022-09-28 05:34 UTC, jaemolihm commented
The phonon feature seems very nice. Yes, I will try it.

Just to make sure, you did not implement long-range interaction, right? So the code will work for metals and non-polar insulators, but not for polar insulators (i.e. it will not give LO-TO splitting).

Also, does the `use_ws` option works just as for electrons, just with the atomic positions instead of the Wannier centers?

2022-09-28 07:54 UTC, stepan-tsirkin commented
> Just to make sure, you did not implement long-range interaction, right

not so far. Do you have a reference to look how it should be done?

>  Also, does the use_ws option works just as for electrons, just with the atomic positions instead of the Wannier centers?

exactly

2022-09-28 08:59 UTC, jaemolihm commented
> > Just to make sure, you did not implement long-range interaction, right
> 
> not so far. Do you have a reference to look how it should be done?

The original reference is https://journals.aps.org/prb/abstract/10.1103/PhysRevB.55.10355

But the supplemental material of this recent paper is much easier to parse. https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.125.217602
(In QE, only the "DD" (dipole-dipole) term is implemented.)

For lower dimensions, one needs different formulas. For 2D, they are in appendix B of https://arxiv.org/abs/2207.10190
The 1D case is in https://arxiv.org/abs/2208.09887

2022-10-02 08:03 UTC, jaemolihm requested changes
@stepan-tsirkin I fixed one bug: mass factor should be divided after ASR, not before. This effects phonon frequency where there are atoms with different masses.

After this fix, the code seems fine and working well! I left some comments.

2022-10-02 08:03 UTC, jaemolihm commented on wannierberri/data_K.py
> +            e = np.sqrt(np.abs(E))*Ry_eV
Multiply `Ry_eV**2` to `system.Ham_R` instead?

2022-10-02 08:03 UTC, jaemolihm commented on wannierberri/system/system_phonon_qe.py
> +            freq_cmm1 = np.array( [data.frequencies_thz_cmm1.__getattr__(f"omega_{j+1}").cdata.split()[1] for j in range(3*number_of_atoms)],dtype=float  )
Remove variables that are not used, and read geometry info only once (from first q point)

2022-10-02 08:03 UTC, jaemolihm commented on wannierberri/system/system_phonon_qe.py
> +        for q,dyn_mat in zip(q_points,dynamical_mat):
Remove debug prints

2022-10-02 08:05 UTC, jaemolihm commented on tests/data/Si_phonons/si.dyn0
> +   2   2   2
Please add QE input files as well as pseudopotential file for the phonon test data

2022-10-02 08:05 UTC, jaemolihm commented on wannierberri/data_K.py
> +            e = np.sqrt(np.abs(E))*Ry_eV
Also `returrns`

2022-12-09 15:24 UTC, merged