interface to FPLO code
wannier-berri/wannier-berri pull request #91
Opened 2021-11-14 00:03 UTC by stepan-tsirkin

System_fplo allows to use Wannier functions from the [FPLO](https://www.fplo.de/) code.  

Only the internal terms may be evaluated.

A test is included for bcc Fe (from a 2x2x2 grid)

2021-11-14 02:08 UTC, jaemolihm commented on wannierberri/__system_fplo.py
> +        if self.morb : raise ValueError("System_tb class cannot be used for evaluation of external terms in orbital magnetic moments")
System tb -> fplo

2021-11-14 02:15 UTC, jaemolihm requested changes
Looks good to me.

Do You use wcc true in the test because FPLO does not provide the AA matrix? If so, could you mention thisin system fplo ? (Maybe also a warning (not an error) if use wcc phase is false?).

Or is the AA matrix automatically set to be diagonal using the wann centers when use wcc phase is false? If this is the case, there is no need to do what I said. Then you could also test the non wcc system with the same reference data.

2021-11-14 02:15 UTC, jaemolihm commented on wannierberri/__system_fplo.py
> +        if self.berry : raise ValueError("System_tb class cannot be used for evaluation of external terms of berry curavture")
Tb -> fplo

2021-11-14 02:15 UTC, jaemolihm commented on wannierberri/__system_fplo.py
> +        if self.morb : raise ValueError("System_tb class cannot be used for evaluation of external terms in orbital magnetic moments")
Stystem tb -> fplo

2021-11-14 02:15 UTC, jaemolihm commented on wannierberri/__system_fplo.py
> +#        if self.spin : raise ValueError("System_tb class cannot be used for evaluation of spin properties")
If spin can be used, you can delete this comment

2021-11-14 15:42 UTC, stepan-tsirkin commented
Thanks for comments, @jaemolihm 
Yes, I allowed for external terms with diagonal AA_R matrix (like for TB models) and print a warning that it is not recommended to do so. 

Additional tests pass, and also note that FPLO gives perfectly symmetric WFs. A test checks this also.

Any more comments?

2021-11-15 08:45 UTC, jaemolihm commented
Looks good.

2021-11-15 08:45 UTC, jaemolihm approved these changes

2021-11-15 12:13 UTC, merged

2021-11-19 04:25 UTC, jaemolihm commented
@stepan-tsirkin , I saw a paper on arxiv about Wannier functions in FPLO code : "Symmetry Conserving Maximally Projected Wannier Functions" https://arxiv.org/abs/2111.09652.

I have no experience with FPLO code, so I have some questions. Do you know the following?
1. Is the FPLO WFs just the projection-only WFs of Wannier90 (i.e. `num_iter=0`, `dis_num_iter=0`?)
2. Is there anything one should learn from FPLO in terms of Wannier function method development? Or is it just a new implementation of the same algorithms?

2021-11-20 20:01 UTC, stepan-tsirkin commented
@jaemolihm  , i actually have no experience with the FPLO. Neithew I have seen its source code.

Just some collaborators asked me for the interface and it was easy to do such. They provided a sample of input for tests, so I did not even run FPLO myself. 

But from the test it really comes out that the WFs are symmetric. I also sow the paper, but did not read it in detail.