degen_thresh and degen_Kramers
wannier-berri/wannier-berri pull request #94
Opened 2021-11-19 01:54 UTC by stepan-tsirkin

Now `degen_thresh` is an input parameter for all FermiOcean quantities. 
Also add a parameter `degen_Kramers` which makes the bands (0,1) , (2,3), ...considered always as degenerate, regardless of actual splitting. This may be used only for PT-symmetric systems

Included a test , whith a model  that slightl;y breaks PT symmetyry, and check that `degen_Kramers=True` and `degen_thresh=0.05` give the same results.

2021-11-20 01:48 UTC, jaemolihm requested changes

2021-11-20 01:48 UTC, jaemolihm commented on wannierberri/models.py
> +    t : float
Use hop1 and hop2 to be consistent with other models

2021-11-20 01:48 UTC, jaemolihm commented on tests/test_integrate.py
> +            data2=result.results.get(qfull1).data
qfull2?

2021-11-20 01:48 UTC, jaemolihm commented on tests/test_integrate.py
> +            print (qfull1,qfull2)
Delete this line

2021-11-20 01:48 UTC, jaemolihm commented
I left some minor comments. Looks hood otherise.

2021-11-20 02:53 UTC, jaemolihm commented
Instead of writing degen thresh = 1e-4, degen kramers false in every quantities, what about passing **parameters to FermiOcean?

2021-11-20 17:30 UTC, stepan-tsirkin commented
> Instead of writing degen thresh = 1e-4, degen kramers false in every quantities, what about passing **parameters to FermiOcean? 

The problem is that `**parameters` are passed to the formula, 
Well, if `**parameters` includes `degen_thresh` , and error will **not** occur in a Formula, just a useless property will appear in it. Athough it is not nice
But if we pass `external_terms` to `FermiOcean` trough `**paramerters` there will be an error. 

Do you know an elegant solution to this problem? If you have, you can mkake another  PR in future.

>Also **kwargs (keyword arguments) is more idiomatic in python.

For the reason above, maybe rename it to `**formula_kwargs` , to distinguish from other parameters.

2021-11-21 09:27 UTC, jaemolihm commented
I see. I can't think of a good solution now; I'll make a PR if I find one.

2021-11-21 10:56 UTC, merged